export default {
  login: "rayenmehrez77",
  id: 54637377,
  node_id: "MDQ6VXNlcjU0NjM3Mzc3",
  avatar_url: "https://avatars.githubusercontent.com/u/54637377?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/rayenmehrez77",
  html_url: "https://github.com/rayenmehrez77",
  followers_url: "https://api.github.com/users/rayenmehrez77/followers",
  following_url: "https://api.github.com/users/rayenmehrez77/following{/other_user}",
  gists_url: "https://api.github.com/users/rayenmehrez77/gists{/gist_id}",
  starred_url: "https://api.github.com/users/rayenmehrez77/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/rayenmehrez77/subscriptions",
  organizations_url: "https://api.github.com/users/rayenmehrez77/orgs",
  repos_url: "https://api.github.com/users/rayenmehrez77/repos",
  events_url: "https://api.github.com/users/rayenmehrez77/events{/privacy}",
  received_events_url: "https://api.github.com/users/rayenmehrez77/received_events",
  type: "User",
  site_admin: false,
  name: "Rayen Mehrez",
  company: null,
  blog: "rayenmehrez.netlify.com/",
  location: "Tunisia",
  email: null,
  hireable: null,
  bio: "My Name is Rayen Mehrez I'm a front-end web developer. I have a passion working with React.js",
  twitter_username: null,
  public_repos: 47,
  public_gists: 0,
  followers: 1,
  following: 7,
  created_at: "2019-08-28T16:08:44Z",
  updated_at: "2021-04-16T12:59:20Z"
  }